#!/usr/bin/env bash

file="$@"
# shift

# case "${file}" in
#   --system|--global|--local)
#     ;;
#   -f|--file|--blob)
#     file="${file} ${1:-}"
#     shift
#     ;;
# esac

read -p "What's your name? " name
[[ -n "${name}" ]] && git config ${file} user.name "${name}"
read -p "What's your email? " email
[[ -n "${email}" ]] && git config ${file} user.email "${email}"

git config ${file} column.ui auto
git config ${file} core.editor vi

git config ${file} diff.algorithm histogram
git config ${file} diff.colorMoved plain
git config ${file} diff.mnemonicPrefix true
git config ${file} diff.renames true
git config ${file} diff.submodule log

git config ${file} merge.conflictstyle zdiff3

git config ${file} pull.ff only
git config ${file} push.autoSetupRemote true
git config ${file} push.default simple

git config ${file} tag.sort version:refname

# git config $file alias.co checkout
# git config $file alias.ci commit
git config ${file} alias.branch-default '!git remote show origin | sed -n "/HEAD branch/s/.*: //p"'
git config ${file} alias.branch-prune '!git branch --merged "origin/$(git branch-default)" | grep -v "$(git branch-default)" > /tmp/git-branch-merged && vi /tmp/git-branch-merged && xargs git branch -d < /tmp/git-branch-merged'
git config ${file} alias.discard 'checkout HEAD --'
git config ${file} alias.unstage 'reset HEAD --'
git config ${file} alias.ff 'merge --ff-only'
git config ${file} alias.graph 'log --graph --decorate'
git config ${file} alias.pdtop 'rev-parse --show-toplevel'
git config ${file} alias.pdpre 'rev-parse --show-prefix'

git config --list --show-scope
