#!/usr/bin/env bash

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

################################################################################
# XDG Paths
################################################################################
export XDG_BIN_HOME="${XDG_BIN_HOME:-${HOME}/.local/bin}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
export XDG_INCLUDE_HOME="${XDG_LIB_HOME:-${HOME}/.local/include}"
export XDG_LIB_HOME="${XDG_LIB_HOME:-${HOME}/.local/lib}"

mkdir -p "${XDG_BIN_HOME}"
mkdir -p "${XDG_CACHE_HOME}"
mkdir -p "${XDG_CONFIG_HOME}"
mkdir -p "${XDG_DATA_HOME}"
mkdir -p "${XDG_INCLUDE_HOME}"
mkdir -p "${XDG_LIB_HOME}"

################################################################################
# Shell Resource Configuration File
################################################################################
# TODO: detect default shell
export SHRC="${ZDOTDIR:-${HOME}}/.zshrc"

################################################################################
# Function: Install
################################################################################
# TODO: replace with bash scripts library
install() {
  if which apt 2>&1 > /dev/null; then
    apt install "$@"
  fi
  if which brew 2>&1 > /dev/null; then
    brew install "$@"
  fi
}
