#!/usr/bin/env bash

cat <<EOF >> "${ZDOTDIR:-${HOME}}/.zshrc"

################################################################################
# GitLab
################################################################################
source "\${ZDOTDIR:-\${HOME}}/.gitlab"
EOF

cat <<EOF > "${ZDOTDIR:-${HOME}}/.gitlab"
################################################################################
# GitLab
################################################################################
export GITLAB_TOKEN="${GITLAB_TOKEN}"

gitlab-token() {
  local token="\${1}"
  if [[ -z "\${token}" ]]; then
    echo "\${GITLAB_TOKEN}"
  else
    sed -E -i "" -e "/^export GITLAB_TOKEN=.*/s//export GITLAB_TOKEN=\${token}/"\\
      "\${ZDOTDIR:-\${HOME}}/.gitlab" > /dev/null
    echo "\${token}" | docker login -u "${GITLAB_USER:-${USER}}" gitlab-registry.checkrhq.net --password-stdin
  fi
}
EOF

echo "[GitLab] To update your token, run: gitlab-token TOKEN"
