#!/usr/bin/env python
#
# See https://developer.apple.com/library/archive/technotes/tn2450/_index.html

import json
import os

mappings = [
  { 'src': 0x65, 'dst': 0xE7},         # Application => GUI (Windows/Apple)
]

def convert(m):
  return {
    "HIDKeyboardModifierMappingSrc": 0x700000000 | m["src"],
    "HIDKeyboardModifierMappingDst": 0x700000000 | m["dst"],
  }

mappings = map(convert, mappings)
properties = {
  "UserKeyMapping": mappings,
}
properties = json.dumps(properties)

command = "hidutil property --set '{}'".format(properties)

os.system(command)
