#!/usr/bin/env ruby
#
# See https://developer.apple.com/library/archive/technotes/tn2450/_index.html

require "json"

mappings = [
  { src: 0x65, dst: 0xE7 },         # Application => GUI (Windows/Apple)
]
mappings.map! do |m|
  {
    HIDKeyboardModifierMappingSrc: 0x700000000 | m[:src],
    HIDKeyboardModifierMappingDst: 0x700000000 | m[:dst],
  }
end

properties = {
  UserKeyMapping: mappings,
}
properties = JSON.dump(properties)

command = "hidutil property --set '#{properties}'"

exec(command)
