#!/usr/bin/env bash

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../" && pwd)"
source "${root}/bootstrap" || exit 1

################################################################################
# ASDF Tools Manager
################################################################################

install asdf

cat <<EOF >> "${SHRC}"

################################################################################
# ASDF Tool Manager
################################################################################
export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME}/asdf"
export ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
source "$(brew --prefix asdf)/asdf.sh"
EOF

source "${SHRC}"

asdf plugin-add ruby
asdf plugin-add golang
asdf plugin-add nodejs
asdf plugin-add python

bash "${ASDF_DATA_DIR}/plugins/nodejs/bin/import-release-team-keyring"

cat <<EOF > "${ASDF_CONFIG_FILE}"
legacy_version_file = yes
EOF
