#!/usr/bin/env zsh

file="${(%):-%x}"
root="$(cd "$(dirname "${file}")/../" && pwd)"

echo "" > /tmp/tasks
tasks() {
  local task="${1}"
  if [[ -z "${task}" ]]; then
    cat /tmp/tasks
  else
    echo "${tasks}" >> /tmp/tasks
  fi
}

################################################################################
# Shell
################################################################################
echo "Configuring ZSH"

"${root}/shell/zsh/configure"

################################################################################
# Xcode CLI Tools
################################################################################
# echo "Configuring XCode"
# xcode-select --install

################################################################################
# Git
################################################################################
echo "Configuring Git"

"${root}/git/config" --global

################################################################################
# Homebrew
################################################################################
echo "Configuring Homebrew"

"${root}/homebrew/install"

cat <<EOF >> "${ZDOTDIR:-${HOME}}/.zshrc"

################################################################################
# Homebrew
################################################################################
eval "\$(/opt/homebrew/bin/brew shellenv)"
EOF

source "${ZDOTDIR:-${HOME}}/.zshrc"

brew install openssl

################################################################################
# GPG
################################################################################
echo "Configuring GPG"

"${root}/gpg/install"

################################################################################
# SSH
################################################################################
echo "Configuring SSH"

"${root}/ssh/configure"


################################################################################
# ASDF Tools Manager
################################################################################
echo "Configuring ASDF"

"${root}/asdf/install"


################################################################################
# Artifactory
################################################################################
echo "Configuring Artifactory"

"${root}/artifactory/configure"


################################################################################
# Ruby Bundler
################################################################################
echo "Configuring Ruby Bundler"

cat <<EOF >> "${ZDOTDIR:-${HOME}}/.zshrc"

################################################################################
# Ruby Bundler
################################################################################
export BUNDLE_USER_CACHE=\${XDG_CACHE_HOME}/bundle
export BUNDLE_USER_CONFIG=\${XDG_CONFIG_HOME}/bundle
export BUNDLE_USER_HOME=\${XDG_DATA_HOME}/bundle
EOF

source "${ZDOTDIR:-${HOME}}/.zshrc"

cat <<EOF > "${BUNDLE_USER_CONFIG}"
---
BUNDLE_GEM__CHANGELOG: "true"
BUNDLE_GEM__CI: "gitlab"
BUNDLE_GEM__COC: "false"
BUNDLE_GEM__LINTER: "rubocop"
BUNDLE_GEM__MIT: "false"
BUNDLE_GEM__TEST: "rspec"
EOF

################################################################################
# Gemfury
################################################################################
echo "Configuring Gemfury"

cat <<EOF >> "${ZDOTDIR:-${HOME}}/.zshrc"

################################################################################
# Gemfury
################################################################################
source "\${ZDOTDIR:-\${HOME}}/.gemfury"
EOF

cat <<EOF > "${ZDOTDIR:-${HOME}}/.gemfury"
################################################################################
# Gemfury
################################################################################
export GEMFURY_TOKEN="${GEMFURY_TOKEN}"

gemfury-token() {
  local token="\${1}"
  if [[ -z "\${token}" ]]; then
    echo "\${GEMFURY_TOKEN}"
  else
    sed -E -i "" -e "/^export GEMFURY_TOKEN=.*/s//export GEMFURY_TOKEN=\${token}/" \\
      "\${ZDOTDIR:-\${HOME}}/.gemfury" > /dev/null
    bundle config set --global gem.fury.io "\${token}"
  fi
}
EOF

echo "[Gemfury] To update your token, run: gemfury-token TOKEN"

################################################################################
# GitLab
################################################################################
echo "Configuring GitLab"

cat <<EOF >> "${ZDOTDIR:-${HOME}}/.zshrc"

################################################################################
# GitLab
################################################################################
source "\${ZDOTDIR:-\${HOME}}/.gitlab"
EOF

cat <<EOF > "${ZDOTDIR:-${HOME}}/.gitlab"
################################################################################
# GitLab
################################################################################
export GITLAB_TOKEN="${GITLAB_TOKEN}"

gitlab-token() {
  local token="\${1}"
  if [[ -z "\${token}" ]]; then
    echo "\${GITLAB_TOKEN}"
  else
    sed -E -i "" -e "/^export GITLAB_TOKEN=.*/s//export GITLAB_TOKEN=\${token}/"\\
      "\${ZDOTDIR:-\${HOME}}/.gitlab" > /dev/null
    echo "\${token}" | docker login -u "${GITLAB_USER:-${USER}}" gitlab-registry.checkrhq.net --password-stdin
  fi
}
EOF

echo "[GitLab] To update your token, run: gitlab-token TOKEN"

################################################################################
# Puma Dev
################################################################################
echo "Configuring Puma Dev"

brew install puma/puma/puma-dev
sudo puma-dev -setup
puma-dev -install -d localhost

################################################################################
# Teleport
################################################################################
echo "Configuring Teleport"

cat <<EOF >> "${ZDOTDIR:-${HOME}}/.zshrc"

################################################################################
# Teleport
################################################################################
export TELEPORT_AUTH="gitlab"
export TELEPORT_PROXY="heimdallr.checkrhq.net"
EOF

if command -v tsh &> /dev/null; then
  echo "[Teleport] Already installed"
else
  open "https://goteleport.com/download/?os=macos"
fi

################################################################################
# Docker
################################################################################
echo "Configuring Docker"

if command -v docker &> /dev/null; then
  echo "[Docker] Already installed"
else
  open "https://docs.docker.com/get-docker/"
fi
